version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    volumes:
      - ./data:/data

    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.2"
      OPS: "X__gamer"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      EXEC_DIRECTLY: true
      INIT_MEMORY: 4G
      MAX_MEMORY: 6G
      VIEW_DISTANCE: 20
